//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCenterProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int CourseID { get; set; }
        public int TraineeID { get; set; }
        public string Status { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Trainee Trainee { get; set; }
    }
}
